Update JenkinsFile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -2,28 +2,65 @@ pipeline {
     agent any
 
     environment {
-        
-        TERRAFORM_DIR = "/usr/local/bin/terraform"
+        REPO_URL = 'https://github.com/pavithra-m13/Docker_terraform_Pipeline.git'
+        IMAGE_NAME = 'my-apache'
+        CONTAINER_NAME = 'apache-container'
+        APACHE_PORT = '8080'
     }
 
     stages {
         stage('Clone Repository') {
             steps {
-                git branch: 'master', url: 'https://github.com/pavithra-m13/Docker_terraform_Pipeline.git'
+                echo 'Cloning Git Repository...'
+                git branch: 'master', url: REPO_URL
             }
         }
-       
-       stage('Deploy Website to Apache') {
-    steps {
-        sh '''
-            echo "Deploying to Apache server..."
-            docker cp apache/public-html/. apache-container:/usr/local/apache2/htdocs/
-            docker restart apache-container
-        '''
+
+        stage('Build Docker Image') {
+            steps {
+                echo 'Building Apache Docker Image...'
+                sh '''
+                    docker build -t ${IMAGE_NAME} .
+                '''
+            }
+        }
+
+        stage('Run Apache Container') {
+            steps {
+                echo 'Checking if the container is already running...'
+                script {
+                    def containerExists = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${CONTAINER_NAME} || true", returnStdout: true).trim()
+                    if (containerExists) {
+                        echo 'Stopping and removing existing container...'
+                        sh "docker stop ${CONTAINER_NAME} || true"
+                        sh "docker rm ${CONTAINER_NAME} || true"
+                    }
+                }
+                
+                echo 'Starting a new Apache container...'
+                sh '''
+                    docker run -d --name ${CONTAINER_NAME} -p ${APACHE_PORT}:80 ${IMAGE_NAME}
+                '''
+            }
+        }
+
+        stage('Deploy Website Files') {
+            steps {
+                echo 'Deploying website files to Apache server...'
+                sh '''
+                    docker cp apache/public-html/. ${CONTAINER_NAME}:/usr/local/apache2/htdocs/
+                    docker restart ${CONTAINER_NAME}
+                '''
+            }
+        }
     }
-}
 
-
-        
+    post {
+        success {
+            echo 'Deployment Successful! Website is available at http://localhost:8080'
+        }
+        failure {
+            echo 'Deployment Failed! Check the logs for details.'
+        }
     }
 }
